version: '3'

services:
  storage:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    env_file:
      - .env
    volumes:
      - data-1:/data1
      - data-2:/data2

volumes:
  data-1:
  data-2:
